baseurl = "https://example.org/"
languageCode = "UTF-8"
defaultContentLanguage = "ja"
title = "Aki Koi"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Aki × koi"

		[params.navigation.links]
			about     = "About"
			portfolio  = "portfolio"
			services  = "Services"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "恋する秋タビ。"
		subtitle   = "秋田で始まる恋、恋から始まる秋田。新しい体験はどきどきするもの。まだみたことのない、恋する秋田を旅してみませんか。"
		buttonText = "サインアップ"


	# About section
	[params.about]
		headline    = "旅先でのひとときの出会いは、一生の思い出になる。"
		description = "説明文"
		buttonText  = "サインアップ"


	# Service section
	[params.services]
		headline = "サービスの流れ"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "魅力的なスポット。"
            description = "乳頭温泉で疲れを癒したり、角館武家屋敷で桜を見たり。秋田ならではの観光スポットに無料でご招待します。"

        [[params.services.list]]
			icon = "fa-calendar"
			title = "日程を選ぶ。"
			description = "ちょっと出かけたい休日を選ぶだけ。お好みに合わせた体験プランとお供の相手がマッチングされます。"

		[[params.services.list]]
            icon = "fa-envelope"
            title = "チャットする。"
            description = "一緒に旅する相手とメッセージをやりとりして、どんなことに興味があるか、どこに行ってみたいか意見を交換しましょう。"

        [[params.services.list]]
            icon = "fa-heart"
            title = "イベントを体験する。"
            description = "マッチング相手と一緒にスポットに出かけましょう。指定スポットに行くと旅行資金が援助されます。"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "さあ始めよう!!"

		[params.aside.button]
			text = "サインアップ"
			link = "//google.com/"

	# Contact section
	[params.contact]
		headline = "Contact"
		description = "連絡先はこちら。"
		phone = "123-456-6789"
		email = "akitabi@akita.com"

	# Google Maps section
	 #[params.location]
		#latitude  = "34.007850"
		#longitude = "-118.499305"
		#maps_api_key = ""
